"""create quote_requests table

Revision ID: 609b64ba7793
Revises: 
Create Date: 2026-05-08 17:30:46.461501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609b64ba7793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.String(length=50), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_requests')
    # ### end Alembic commands ###
